apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nginx-service
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.port }}
    targetPort: {{ .Values.port }}
  selector:
    app: nginx